In [1]:
#1.Read the three csv files which contains the score of same students in term1 for each Subject


import pandas as pd
import numpy as np
import os


os.chdir('C:\\Users\\Aman Verma\\OneDrive\\Desktop\\Topmentor Assignment\\PYTHON\\CS-16 Data_Transformation-2\\')
os.getcwd()

math_data = pd.read_csv("MathScoreTerm1.csv")
math_data.head()

ds_data = pd.read_csv("DSScoreTerm1.csv")
ds_data.head()

physics_data = pd.read_csv("PhysicsScoreTerm1.csv")
physics_data.head()

             Name  Score  Age         Ethinicity  Subject Sex  ID
0  AI-KYUNG CHUNG   84.0   18     White American  Physics   M   1
1     ALAN HARVEY   81.0   19  European American  Physics   M   2
2    ALAN REYNAUD   41.0   19  European American  Physics   M   3
3  ALBERT CENDANA   78.0   18     White American  Physics   M   4
4  ALBERT HOLT JR   78.0   18     White American  Physics   F   5

In [2]:
#2.Remove the name and ethnicity column (to ensure confidentiality)

math_data = math_data.drop(['Name','Ethinicity'], axis=1)
print(math_data.head())


ds_data = ds_data.drop(['Name','Ethinicity'], axis=1)
print(ds_data.head())



physics_data = physics_data.drop(['Name','Ethinicity'], axis=1)
print(physics_data.head())

   Score  Age Subject Sex  ID
0   88.0   18   Maths   M   1
1   85.0   19   Maths   M   2
2   45.0   19   Maths   M   3
3   82.0   18   Maths   M   4
4   82.0   18   Maths   F   5
   Score  Age        Subject Sex  ID
0   82.0   18  Data Structue   M   1
1   79.0   19  Data Structue   M   2
2   39.0   19  Data Structue   M   3
3   76.0   18  Data Structue   M   4
4   76.0   18  Data Structue   F   5
   Score  Age  Subject Sex  ID
0   84.0   18  Physics   M   1
1   81.0   19  Physics   M   2
2   41.0   19  Physics   M   3
3   78.0   18  Physics   M   4
4   78.0   18  Physics   F   5

In [8]:
#3.Fill missing score data with zero

#Maths Data 

# print Summary of missing values in  Maths Data

print (math_data.isnull().sum())

Score      3
Age        0
Subject    0
Sex        0
ID         0
dtype: int64

In [11]:
# Fill Missing Scores with 0

math_data['Score'] = math_data['Score'].fillna(0)
# Check Again if values are filled correctly

print (math_data.isnull().sum())

Score      0
Age        0
Subject    0
Sex        0
ID         0
dtype: int64

In [14]:
#Data Science Data 
# print Summary of missing values in Data Science Data

print (ds_data.isnull().sum())

Score      8
Age        0
Subject    0
Sex        0
ID         0
dtype: int64

In [16]:
# Fill Missing Scores with 0

ds_data['Score'] = ds_data['Score'].fillna(0)
print (ds_data.isnull().sum())

Score      0
Age        0
Subject    0
Sex        0
ID         0
dtype: int64

In [17]:
# print Summary of missing values in Physics Data

print (physics_data.isnull().sum())

Score      6
Age        0
Subject    0
Sex        0
ID         0
dtype: int64

In [19]:
# Fill Missing Scores with 0

physics_data['Score'] = physics_data['Score'].fillna(0)

print (physics_data.isnull().sum())

Score      0
Age        0
Subject    0
Sex        0
ID         0
dtype: int64

In [20]:
#4.Merge the three files

# Merge all data - List is created 

all_data =[math_data,ds_data,physics_data]
all_data

[     Score  Age Subject Sex   ID
 0     88.0   18   Maths   M    1
 1     85.0   19   Maths   M    2
 2     45.0   19   Maths   M    3
 3     82.0   18   Maths   M    4
 4     82.0   18   Maths   F    5
 ..     ...  ...     ...  ..  ...
 594   45.0   19   Maths   F  595
 595   75.0   18   Maths   M  596
 596   53.0   20   Maths   M  597
 597   75.0   20   Maths   M  598
 598   88.0   19   Maths   M  599

 [599 rows x 5 columns],
      Score  Age        Subject Sex   ID
 0     82.0   18  Data Structue   M    1
 1     79.0   19  Data Structue   M    2
 2     39.0   19  Data Structue   M    3
 3     76.0   18  Data Structue   M    4
 4     76.0   18  Data Structue   F    5
 ..     ...  ...            ...  ..  ...
 594   39.0   19  Data Structue   F  595
 595   69.0   18  Data Structue   M  596
 596   47.0   20  Data Structue   M  597
 597   69.0   20  Data Structue   M  598
 598    0.0   19  Data Structue   M  599

 [599 rows x 5 columns],
      Score  Age  Subject Sex   ID
 0     84.0   18  Physics   M    1
 1     81.0   19  Physics   M    2
 2     41.0   19  Physics   M    3
 3     78.0   18  Physics   M    4
 4     78.0   18  Physics   F    5
 ..     ...  ...      ...  ..  ...
 594   41.0   19  Physics   F  595
 595   71.0   18  Physics   M  596
 596   49.0   20  Physics   M  597
 597   71.0   20  Physics   M  598
 598   69.0   19  Physics   M  599

 [599 rows x 5 columns]]

In [21]:
#5.Change Sex(M/F) Column to 1/2 for further analysis

# Convert Sex M to 1 and F to 2

for dataset in all_data:
    dataset['Sex'] = dataset['Sex'].map({'M': 1, 'F': 2}).astype(int)


all_data_df = pd.concat(all_data)
all_data_df

     Score  Age  Subject  Sex   ID
0     88.0   18    Maths    1    1
1     85.0   19    Maths    1    2
2     45.0   19    Maths    1    3
3     82.0   18    Maths    1    4
4     82.0   18    Maths    2    5
..     ...  ...      ...  ...  ...
594   41.0   19  Physics    2  595
595   71.0   18  Physics    1  596
596   49.0   20  Physics    1  597
597   71.0   20  Physics    1  598
598   69.0   19  Physics    1  599

[1797 rows x 5 columns]

In [22]:
#6.Store the data in new file – ScoreFinal.csv

os.getcwd()

all_data_df.to_csv('ScoreFinal.csv',index=False)

print ("Done")

Done